joinup:
  db:
    host: ${DB_HOST}
    port: 5432
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: joinup-course-service-dev
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: 0
  rabbitmq:
    host: ${MQ_HOST}
    port: 5672
    virtual-host: /joinup-dev
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
  nacos:
    addr: ${NACOS_ADDR}
    namespace: ""