joinup:
  nacos:
    addr: ${NACOS_ADDR}
    namespace: ""
  rabbitmq:
    host: ${MQ_HOST}
    port: 5672
    virtual-host: /joinup-dev
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
  jwt:
    password: ${JWT_PASSWORD}
    location: classpath:joinup.jks
    alias: joinup
    tokenTTL: 180m