joinup:
  db:
    host: ${DB_HOST}
    port: 3306
    database: message-center-dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  nacos:
    namespace: ""
  rabbitmq:
    host: ${MQ_HOST}
    port: 5672
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}