joinup:
  db:
    host: ${DB_HOST}
    port: 5432
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: joinup-user-service-prod
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 1
  jwt:
    location: classpath:joinup-prod.jks
    alias: joinup-prod
    password: ${JWT_PASSWORD}
    tokenTTL: 30m
  aes:
    key: ${AES_KEY}
    iv: ${AES_IV}
  wx:
    miniapp:
      app-id: ${APP_ID}
      app-secret: ${APP_SECRET}


spring:
  flyway:
    baseline-version: 1


github:
  oauth:
    redirect-uri: http://39.105.96.112/api/user/auth/github/callback


frontend:
  redirect:
    # 允许的前端回调地址域名白名单
    allowed-domains:
      - https://101.42.43.228
      - http://101.42.43.228
      - http://39.105.96.112
    # 是否允许相对路径
    allow-relative-paths: true